gzip_assets: off
compress_assets: off

javascripts:
  'mixin_core':
    - build/mixin_core.js
    - build/mixin_core_statistics.js

  'mixin':
    - build/mixin_core.js
    - build/mixin_core_statistics.js
    - build/mixin_backbone_events.js
    - build/mixin_ref_count.js
    - build/mixin_flags.js
    - build/mixin_auto_memory.js
    - build/mixin_backbone_local_collection.js
    - build/mixin_timeouts.js
    - build/mixin_subscriptions.js

